// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyznSbCcRrCvtMGx95t8FRy9jqpoJxHIE',
    appId: '1:210613747444:web:dc3d16b652ab8f4472a8a1',
    messagingSenderId: '210613747444',
    projectId: 'flutterflexmen-35373',
    authDomain: 'flutterflexmen-35373.firebaseapp.com',
    storageBucket: 'flutterflexmen-35373.firebasestorage.app',
    measurementId: 'G-08NPYP5V1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBIoC36b55w-G5JyfR7I9ykPZ6jrI0HTI',
    appId: '1:210613747444:android:2dfa0bcd4cdf900072a8a1',
    messagingSenderId: '210613747444',
    projectId: 'flutterflexmen-35373',
    storageBucket: 'flutterflexmen-35373.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_vVBjPIHUB_wLxHTzynLy1P3-_PaSjrA',
    appId: '1:210613747444:ios:e60dca9fcb976dfa72a8a1',
    messagingSenderId: '210613747444',
    projectId: 'flutterflexmen-35373',
    storageBucket: 'flutterflexmen-35373.firebasestorage.app',
    iosBundleId: 'com.example.flutterflexmenv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyznSbCcRrCvtMGx95t8FRy9jqpoJxHIE',
    appId: '1:210613747444:web:3cbc0878d30d643472a8a1',
    messagingSenderId: '210613747444',
    projectId: 'flutterflexmen-35373',
    authDomain: 'flutterflexmen-35373.firebaseapp.com',
    storageBucket: 'flutterflexmen-35373.firebasestorage.app',
    measurementId: 'G-PPK86K4VZW',
  );

}